In [2]:
import numpy as np
import scipy.signal as scisig

layer0 = np.random.rand(3,3)
layer0[:,:] =  [[0.25, 0.0, 0.0],
                  [0.0, 1.00, 0.0],
                  [0.0, 0.0, 0.0]]

kernel_size = (3,3)
number_filters = 10

filters = np.random.uniform(-1,1, size=(number_filters, *kernel_size))
def padding(layer:np.ndarray, mode:str = 'zero'):


    padded_ly_size = (layer.shape[0]+2, layer.shape[1]+2)
    padded_ly = np.zeros(padded_ly_size)
    padded_ly[1:-1,1:-1] = layer
   
    if mode == 'continue':
        padded_ly[0,1:-1] = layer[0,:]
        padded_ly[-1,1:-1] = layer[-1,:]

        padded_ly[1:-1,0] = layer[:,0]
        padded_ly[1:-1,-1] = layer[:,-1]

        padded_ly[0,0] = layer[0,0]
        padded_ly[0,-1] = layer[0,-1]
        padded_ly[-1,0] = layer[-1,0]
        padded_ly[-1,-1] = layer[-1,-1]

    return(padded_ly)

padded_ly = padding(layer0, "zero")
feture_maps = np.zeros(shape=(number_filters, *layer0.shape))
layer1 = np.zeros_like(layer0)

filters[0,:,:] = [[0.125, 0.25, 0.125], #making a simple filter so we can see it's effects
                  [0.250, 1.00, 0.250],
                  [0.125, 0.25, 0.125]]
convolved = scisig.convolve(padded_ly, filters[0,:,:], mode="same",method = 'fft') #this is def the hard way to do it
feature_map_1 = convolved[1:-1,1:-1]
feture_maps[0,:,:] = convolved[1:-1,1:-1]


feature_map_1_alt = scisig.convolve(layer0, filters[0,:,:], mode="same", method='fft')

def max_pool(feture_mps):
    
    ft_map = np.max(feture_maps, axis=0)
    return(ft_map)

same_check = feature_map_1 - feature_map_1_alt
print(same_check)  # interestingly, these are not exactly the same

feture_maps[5,2,2] = 10
ft_map = max_pool(feture_maps)

layer1[:,:] = ft_map
print(ft_map)

#next up: think about hwo to do backpropigation with this, mayube build a full network to test it


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  0.00000000e+00  5.55111512e-17]
 [-2.77555756e-17 -5.55111512e-17  2.77555756e-17]]
[[ 0.375    0.3125   0.125  ]
 [ 0.3125   1.03125  0.25   ]
 [ 0.125    0.25    10.     ]]


In [3]:
import numpy as np

i = 3
j = 3
m = 2

k = 2
l = 2

in2 = np.arange(i*j)
in2 = np.reshape(in2, (i,j))
#print(in2)

w2 = np.reshape(np.arange(m*i*j*k*l), (m,i,j,k,l))

out3 = np.reshape(np.arange(k*l), (k,l))
#print(out3)

#out2 = np.tensordot(in2, out3, axes = ((0,0),(0,0)))
#print(out2)

in1 = np.zeros((m, i,j))
in1[0,0,0] = 2
in1[0,1,1] = 10
print (in1)
w1 = np.ones((m, i,j, k,l))
w1[:,:,:,1,1] = 0
w1[0,0,0,0,1] = 0.5
#print (w1)


out = np.tensordot(in1,w1, axes=((0,1,2),(0,1,2)))
print(out)

[[[ 2.  0.  0.]
  [ 0. 10.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]
[[12. 11.]
 [12.  0.]]


In [4]:
W3 = np.zeros((3,2,5))
W3[1,1,0] = 1
print(W3)

delL = np.zeros((5,))
delL[3] = 2
print(delL)

result = np.dot(W3, delL)
print("\n Dot result",result)

result = np.tensordot(W3, delL, axes=((2),(0)))
print("\n Result: ",result)




[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[0. 0. 0. 2. 0.]

 Dot result [[0. 0.]
 [0. 0.]
 [0. 0.]]

 Result:  [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
W3 = np.zeros((3,2,5,3,3))
W3[1,1,0,1,1] = 1
#print(W3)

delL = np.zeros((3,3))
delL[0,0] = 2
delL[1,1] = 2
print(delL)

result = np.dot(W3, delL)
print("\n Dot result",result)

result = np.tensordot(W3, delL, axes=((3,4),(0,1)))
print("\n Result: ",result)


[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]

 Dot result [[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 2. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



In [ ]:
A1 = np.random.rand(5)
Z1 = np.random.rand(5)

Expected = np.random.rand(5)

print(A1,"\n",Z1,"\n",Expected)

result = np.tensordot((Expected-A1), Z1, axes=1)
#tensordot axes = 0:  Full expansion
#tensordot axes = 1:  sum all of axis 1
print("result: ", result.shape, "\n", result)

result = (Expected-A1) * Z1
print("result: ", result.shape, "\n", result)

A1 = np.random.rand(5,5)
Z1 = np.random.rand(5,5)

Expected = np.random.rand(5,5)

result = (Expected-A1) * Z1
print("result: ", result.shape, "\n", result)

In [2]:
import numpy as np
input_array = np.ones(shape=(32, 28,28))

feature_maps = np.ones(shape=(64, 28,28))


for i in range(input_array.shape[0]):
    #print(i)
    for j in range(feature_maps.shape[0]):
        #print(j)
        pass
    

In [11]:
import numpy as np

A1 = np.random.rand(2,2,3)
print(A1)
S1 = np.ones((2,2))



result = np.repeat(np.repeat(A1, 2, axis=0), 2, axis=1)

print(result.shape)
print(result)


[[[0.00320484 0.28757918 0.08161119]
  [0.4400853  0.04841528 0.86056639]]

 [[0.22994848 0.77918058 0.38983267]
  [0.27780337 0.42507947 0.02992971]]]
(4, 4, 3)
[[[0.00320484 0.28757918 0.08161119]
  [0.00320484 0.28757918 0.08161119]
  [0.4400853  0.04841528 0.86056639]
  [0.4400853  0.04841528 0.86056639]]

 [[0.00320484 0.28757918 0.08161119]
  [0.00320484 0.28757918 0.08161119]
  [0.4400853  0.04841528 0.86056639]
  [0.4400853  0.04841528 0.86056639]]

 [[0.22994848 0.77918058 0.38983267]
  [0.22994848 0.77918058 0.38983267]
  [0.27780337 0.42507947 0.02992971]
  [0.27780337 0.42507947 0.02992971]]

 [[0.22994848 0.77918058 0.38983267]
  [0.22994848 0.77918058 0.38983267]
  [0.27780337 0.42507947 0.02992971]
  [0.27780337 0.42507947 0.02992971]]]
