In [ ]:
import numpy as np
import scipy.signal as scisig

layer0 = np.random.rand(3,3)
layer0[:,:] =  [[0.25, 0.0, 0.0],
                  [0.0, 1.00, 0.0],
                  [0.0, 0.0, 0.0]]

kernel_size = (3,3)
number_filters = 10

filters = np.random.uniform(-1,1, size=(number_filters, *kernel_size))
def padding(layer:np.ndarray):
    padded_ly_size = (layer.shape[0]+2, layer.shape[1]+2)
    padded_ly = np.zeros(padded_ly_size)
    padded_ly[1:-1,1:-1] = layer
   
    padded_ly[0,1:-1] = layer[0,:]
    padded_ly[-1,1:-1] = layer[-1,:]

    padded_ly[1:-1,0] = layer[:,0]
    padded_ly[1:-1,-1] = layer[:,-1]

    padded_ly[0,0] = layer[0,0]
    padded_ly[0,-1] = layer[0,-1]
    padded_ly[-1,0] = layer[-1,0]
    padded_ly[-1,-1] = layer[-1,-1]

    return(padded_ly)

padded_ly = padding(layer0)
feture_maps = np.zeros(shape=(number_filters, *layer0.shape))
layer1 = np.zeros_like(layer0)

filters[0,:,:] = [[0.125, 0.25, 0.125], #making a simple filter so we can see it's effects
                  [0.250, 1.00, 0.250],
                  [0.125, 0.25, 0.125]]
convolved = scisig.convolve(padded_ly, filters[0,:,:], mode="same",method = 'fft') #this is def the hard way to do it
feature_map_1 = convolved[1:-1,1:-1]
feture_maps[0,:,:] = convolved[1:-1,1:-1]


feature_map_1_alt = scisig.convolve(layer0, filters[0,:,:], mode="same", method='fft')

def max_pool(feture_mps):
    
    ft_map = np.max(feture_maps, axis=0)
    return(ft_map)

same_check = feature_map_1 - feature_map_1_alt
print(same_check)  # interestingly, these are not exactly the same

feture_maps[5,2,2] = 10
ft_map = max_pool(feture_maps)

layer1[:,:] = ft_map
print(ft_map)

#next up: think about hwo to do backpropigation with this, mayube build a full network to test it


[[ 1.56250000e-01  3.12500000e-02  2.77555756e-17]
 [ 3.12500000e-02  0.00000000e+00  1.11022302e-16]
 [-2.77555756e-17 -5.55111512e-17  5.55111512e-17]]
[[ 0.53125  0.34375  0.125  ]
 [ 0.34375  1.03125  0.25   ]
 [ 0.125    0.25    10.     ]]
